services:
  mariadb:
    image: mariadb:latest
    container_name: go_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: pabiosoft_db
      MARIADB_USER: admin
      MARIADB_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: go_adminer
    restart: always
    ports:
      - "8086:8080" # Port pour accéder à Adminer
    depends_on:
      - mariadb

volumes:
  mariadb_data:









#services:
#  postgres:
#    image: postgres:15
#    container_name: go_postgres # Aussi le Nom d'hôte / Adresse sur pgadmin : go_postgres
#    restart: always
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: pabiosoft_db
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: go_pgadmin
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "8086:80" # Port pour accéder à pgAdmin
#    depends_on:
#      - postgres
#
#volumes:
#  postgres_data:
## admin@pgadmin.com et admin